#!/usr/bin/env python3
"""demo_sudoku_vs_essay — run BOOTSTRAP on TWO fresh problem classes (+ a control),
with adversarial candidates, AFTER predictions are committed in PREDICTION.md.

The RUN is the judge. Domain A should yield κ>0 (only after rejecting a
hallucinated then a soundness-incomplete candidate); Domain B should yield κ=0
ARMOR-ONLY (never a fake gate); Domain C should ABSTAIN.

Run:  python3 run_demo.py        (writes RESULT.md, exits 0 iff predictions held)
"""
import os, sys, json

# import the frozen modules from the parent weapon dir
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import bootstrap_gate as G
import bootstrap_router as R


def _sudoku_harness(verifier, declared):
    """A FRESH harness (built here, not the gate's own self-test fixtures, though
    it reuses the public reference fixtures from the module)."""
    cases = (G._good_cases() + G._broken_cases_full() + G._malformed_cases())
    return {"domain": "sudoku-solution-validity",
            "declared_violation_types": declared,
            "verifier": verifier, "cases": cases}


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = []
    ok = True

    def emit(line=""):
        out.append(line)

    emit("# RESULT — demo_sudoku_vs_essay (the RUN is the judge)")
    emit("")
    emit("*Generated by run_demo.py AFTER PREDICTION.md was committed.*")
    emit("")

    # ----------------------------------------------------------------- #
    # Domain A — sudoku validity: SHOULD yield κ>0, after 2 rejections
    # ----------------------------------------------------------------- #
    declared = ["row_duplicate", "column_duplicate", "box_duplicate"]
    specA = {
        "domain": "sudoku-solution-validity",
        "well_specified": True,
        "has_exact_decidable_property": True,
        "is_judgment_only": False,
        "n_attempts_bound": 3,
        "candidate_harnesses": [
            _sudoku_harness(G._hallucinated_verifier, declared),        # cand 1
            _sudoku_harness(G._sudoku_verifier_no_boxes, declared),     # cand 2
            _sudoku_harness(G.sudoku_verifier, declared),               # cand 3
        ],
    }
    routeA = R.route(specA)
    resA = G.bootstrap_domain(specA)

    emit("## Domain A — sudoku-solution-validity")
    emit(f"- router verdict: **{routeA['verdict']}** (kappa_hint={routeA['kappa_hint']})")
    emit(f"- pipeline outcome: **{resA['outcome']}** (kappa={resA['kappa']})")
    emit("- per-candidate run results:")
    for i, att in enumerate(resA["attempts"], 1):
        emit(f"    {i}. {att['candidate_verdict']} "
             f"({att['reject_reason'] or 'kappa=1, exercised=' + str(att['violation_types_exercised'])})")
    if resA["outcome"] == G.FOUND:
        emit(f"- registration record: `{resA['registration']['name']}` "
             f"(violation types exercised: {resA['registration']['verifier']['violation_types_exercised']})")
        emit(f"- ceiling carried: {resA['ceiling'][:80]}...")
    emit("")

    # ASSERT predictions for A
    a_route_ok = routeA["verdict"] == R.SEARCH and routeA["kappa_hint"] is None
    a_outcome_ok = resA["outcome"] == G.FOUND and resA["kappa"] == 1.0
    a_c1_ok = (resA["attempts"][0]["candidate_verdict"] == G.CAND_REJECTED
               and resA["attempts"][0]["reject_reason"] == G.REJ_HALLUCINATED)
    a_c2_ok = (resA["attempts"][1]["candidate_verdict"] == G.CAND_REJECTED
               and resA["attempts"][1]["reject_reason"] == G.REJ_INCOMPLETE)
    a_c3_ok = resA["attempts"][2]["candidate_verdict"] == G.CAND_VALIDATED
    A_PASS = all([a_route_ok, a_outcome_ok, a_c1_ok, a_c2_ok, a_c3_ok])
    ok = ok and A_PASS
    emit(f"- **Domain A prediction held: {A_PASS}** "
         f"(route={a_route_ok}, outcome={a_outcome_ok}, "
         f"cand1-hallucinated-rejected={a_c1_ok}, cand2-incomplete-rejected={a_c2_ok}, "
         f"cand3-validated={a_c3_ok})")
    emit("")

    # ----------------------------------------------------------------- #
    # Domain B — essay persuasiveness: SHOULD be κ=0 ARMOR-ONLY
    # ----------------------------------------------------------------- #
    specB = {
        "domain": "essay-persuasiveness-quality",
        "well_specified": True,
        "has_exact_decidable_property": False,
        "is_judgment_only": True,
        "n_attempts_bound": 3,
        "candidate_harnesses": [],   # honest searcher finds no exact verifier
    }
    routeB = R.route(specB)
    resB = G.bootstrap_domain(specB)
    emit("## Domain B — essay-persuasiveness-quality")
    emit(f"- router verdict: **{routeB['verdict']}** (kappa_hint={routeB['kappa_hint']})")
    emit(f"- pipeline outcome: **{resB['outcome']}** (kappa={resB['kappa']})")
    emit(f"- why: {resB['why']}")
    emit("")
    b_route_ok = routeB["verdict"] == R.ARMOR and routeB["kappa_hint"] == 0.0
    b_outcome_ok = resB["outcome"] == G.ARMOR_ONLY and resB["kappa"] == 0.0
    B_PASS = b_route_ok and b_outcome_ok
    ok = ok and B_PASS
    emit(f"- **Domain B prediction held: {B_PASS}** "
         f"(route-armor={b_route_ok}, outcome-armor-only-kappa0={b_outcome_ok})")
    emit("")

    # ----------------------------------------------------------------- #
    # Domain C — under-specified: SHOULD ABSTAIN
    # ----------------------------------------------------------------- #
    specC = {"domain": "some vague class", "well_specified": False}
    routeC = R.route(specC)
    resC = G.bootstrap_domain(specC)
    emit("## Domain C — under-specified (control)")
    emit(f"- router verdict: **{routeC['verdict']}**")
    emit(f"- pipeline outcome: **{resC['outcome']}**")
    emit("")
    C_PASS = routeC["verdict"] == R.ABSTAIN and resC["outcome"] == G.ABSTAIN
    ok = ok and C_PASS
    emit(f"- **Domain C prediction held: {C_PASS}**")
    emit("")

    emit("---")
    emit(f"## OVERALL: predictions {'ALL HELD' if ok else 'DID NOT ALL HOLD'} "
         f"(A={A_PASS}, B={B_PASS}, C={C_PASS})")
    emit("")
    emit("Honest note: a κ=1 verifier was earned by the RUN (Domain A cand 3), not by any "
         "self-report; the hallucinated and the soundness-incomplete candidates were REJECTED at "
         "the run step. The validated verifier carries only its known-answer coverage — "
         "toy-passing != frontier-correct.")

    text = "\n".join(out) + "\n"
    with open(os.path.join(here, "RESULT.md"), "w") as f:
        f.write(text)
    print(text)
    print(f"EXIT: {'0 (all predictions held)' if ok else '1 (a prediction FAILED)'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
